version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t lib
      - cd lib
      - zip -r9 ../dep_package.zip .
      - cd ..
      - aws lambda publish-layer-version --layer-name test-pandas --description "added double fn" --zip-file fileb://dep_package.zip --compatible-runtimes python3.9
  build:
    commands:
      - echo "Zipping deployment package..."
      - zip -g deployment_package.zip lambda_function.py
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name pandas-test --zip-file fileb://deployment_package.zip
      - aws lambda update-function-configuration --function-name pandas-test --layers arn:aws:lambda:us-east-1:336369920320:layer:test-pandas:1
      - aws lambda wait function-updated --function-name arn:aws:lambda:us-east-1:336369920320:function:pandas-test
      - aws lambda publish-version --function-name arn:aws:lambda:us-east-1:336369920320:function:pandas-test
      - echo "DONE!!"
